### ISSUE TITLE
compile issue 

### ISSUE THREAD

**Issue by SoniaZotz** [UsefulElectronics/esp32s3_lilygo_8bit_parallel_display_lvgl#6]
![image](https://github.com/UsefulElectronics/esp32s3_lilygo_8bit_parallel_display_lvgl/assets/10633874/31fdd5ce-e8a5-4a87-b0d2-bf579fa0b6d8)

**Comment by UsefulElectronics** [comment]
gpio_pad_select_gpio is idf component function. Make sure you are building your project in a correct directory where ESP-IDF system variable is defined.
